openapi: 3.0.1

info:
  title: Rune Airdrop Backend
  description: "Backend implementation Rune Claiming Process"
  version: 0.0.1

servers:
  - url: "http://localhost:5000/api"
  - url: "https://rune-airdrop-backend.onrender.com/api"

tags:
  - name: Main
  - name: Estimate

paths:
  /different-amount:
    post:
      summary: This endpoint is used to transfer different-amount rune token to different addresses.
      description: This endpoint is used to transfer different-amount rune token to different addresses.
      tags:
        - Main
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/differentAmount"
      responses:
        "200":
          description: Different Amount Rune Airdrop Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Different Amount Rune Airdrop failed!
          content:
            application/json:
              schema:
                type: string

  /same-amount:
    post:
      summary: This endpoint is used to transfer same amount rune token to different addresses.
      description: This endpoint is used to transfer same amount rune token to different addresses.
      tags:
        - Main
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sameAmount"
      responses:
        "200":
          description: Same Amount Rune Airdrop Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Same Amount Rune Airdrop failed!
          content:
            application/json:
              schema:
                type: string

  /runestone-fee:
    get:
      summary: This endpoint is used to calculate each runestone transaction fee.
      description: This endpoint is used to calculate each runestone transaction fee.
      tags:
        - Main
      responses:
        "200":
          description: Calculate redeem runestone transaction Fee Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Calculate redeem runestone transaction Fee failed!
          content:
            application/json:
              schema:
                type: string

  /estimate/different-amount:
    post:
      summary: This endpoint is used to estimate different-amount rune token to different addresses.
      description: This endpoint is used to estimate different-amount rune token to different addresses.
      tags:
        - Estimate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstimateDifferentAmount"
      responses:
        "200":
          description: Different Amount Rune Airdrop Estimate Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Different Amount Rune Airdrop Estimate failed!
          content:
            application/json:
              schema:
                type: string

  /estimate/same-amount:
    post:
      summary: This endpoint is used to estimate same amount rune token to different addresses.
      description: This endpoint is used to estimate same amount rune token to different addresses.
      tags:
        - Estimate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstimateSameAmount"
      responses:
        "200":
          description: Same Amount Rune Airdrop Estimate Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Same Amount Rune Airdrop Estimate failed!
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    differentAmount:
      type: object
      properties:
        rune_id:
          type: string
          example: "2865619:198"
        feeRate:
          type: number
          example: 25
        data:
          type: string
          example:
            [
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },

              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 10,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 15,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 20,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 25,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 30,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 35,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 40,
              },
              {
                "address": "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
                "amount": 45,
              },
            ]
      required:
        - rune_id
        - feeRate
        - data

    sameAmount:
      type: object
      properties:
        rune_id:
          type: string
          example: "2865619:198"
        feeRate:
          type: number
          example: 25
        amount:
          type: number
          example: 10
        addressList:
          type: string
          example:
            [
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
              "tb1p0sd5xq6sz0eg3r9j5df0qk38pgnuqreav2qqtq5jfvwpk3yhzuxqjyttjy",
            ]
      required:
        - rune_id
        - feeRate
        - amount
        - addressList

    EstimateDifferentAmount:
      type: object
      properties:
        feeRate:
          type: number
          example: 25
        size:
          type: number
          example: 5000
      required:
        - feeRate
        - size

    EstimateSameAmount:
      type: object
      properties:
        feeRate:
          type: number
          example: 25
        size:
          type: number
          example: 5000
      required:
        - feeRate
        - size
