openapi: 3.0.1

info:
  title: Rune Airdrop Backend
  description: "Backend implementation Rune Claiming Process (Tips: Once you push runestone transaction, until this transaction is confirmed, can't execute next runestone airdrop.)"
  version: 0.0.1

servers:
  - url: "http://localhost:5000/api"
  - url: "https://rune-airdrop-backend.onrender.com/api"

tags:
  - name: Main
  - name: Estimate

paths:
  /different-amount:
    post:
      summary: Max address amount is 130 addresses. This endpoint is used to transfer different-amount rune token to different addresses.
      description: This endpoint is used to transfer different-amount rune token to different addresses.
      tags:
        - Main
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/differentAmount"
      responses:
        "200":
          description: Different Amount Rune Airdrop Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Different Amount Rune Airdrop failed!
          content:
            application/json:
              schema:
                type: string

  /large-different-amount:
    post:
      summary: Max address amount is 1000 addresses. This endpoint is used to transfer different-amount rune token to different addresses.
      description: Response is pre transaction id. Please copy this transaction id and replace on /large-different-amount-airdrop endpoint request data (txid field). And please execute /large-different-amount-airdrop endpoint.
      tags:
        - Main
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/differentAmount"
      responses:
        "200":
          description: Different Amount Rune Airdrop Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Different Amount Rune Airdrop failed!
          content:
            application/json:
              schema:
                type: string

  /large-different-amount-airdrop:
    post:
      summary: Max address amount is 1000 addresses. This endpoint is used to transfer different-amount rune token to different addresses.
      description: This endpoint is used to transfer different-amount rune token to different addresses.
      tags:
        - Main
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/differentAmountAirdrop"
      responses:
        "200":
          description: Different Amount Rune Airdrop Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Different Amount Rune Airdrop failed!
          content:
            application/json:
              schema:
                type: string
  /same-amount:
    post:
      summary: This endpoint is used to transfer same amount rune token to different addresses.
      description: This endpoint is used to transfer same amount rune token to different addresses.
      tags:
        - Main
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sameAmount"
      responses:
        "200":
          description: Same Amount Rune Airdrop Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Same Amount Rune Airdrop failed!
          content:
            application/json:
              schema:
                type: string

  /runestone-fee:
    get:
      summary: This endpoint is used to calculate each runestone transaction fee.
      description: This endpoint is used to calculate each runestone transaction fee.
      tags:
        - Main
      responses:
        "200":
          description: Calculate redeem runestone transaction Fee Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Calculate redeem runestone transaction Fee failed!
          content:
            application/json:
              schema:
                type: string

  /estimate/different-amount:
    post:
      summary: This endpoint is used to estimate different-amount rune token to different addresses.
      description: This endpoint is used to estimate different-amount rune token to different addresses.
      tags:
        - Estimate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstimateDifferentAmount"
      responses:
        "200":
          description: Different Amount Rune Airdrop Estimate Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Different Amount Rune Airdrop Estimate failed!
          content:
            application/json:
              schema:
                type: string

  /estimate/same-amount:
    post:
      summary: This endpoint is used to estimate same amount rune token to different addresses.
      description: This endpoint is used to estimate same amount rune token to different addresses.
      tags:
        - Estimate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EstimateSameAmount"
      responses:
        "200":
          description: Same Amount Rune Airdrop Estimate Success!
          content:
            application/json:
              schema:
                type: string
        "500":
          description: Same Amount Rune Airdrop Estimate failed!
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    differentAmount:
      type: object
      properties:
        rune_id:
          type: string
          example: "2822267:1023"
        feeRate:
          type: number
          example: 25
        data:
          type: string
          example:
            [
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 10,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 15,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 20,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 25,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 30,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 35,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 40,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 45,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 10,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 15,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 20,
              },
            ]
      required:
        - rune_id
        - feeRate
        - data

    differentAmountAirdrop:
      type: object
      properties:
        rune_id:
          type: string
          example: "2822267:1023"
        feeRate:
          type: number
          example: 25
        txid:
          type: string
          example: "217175dc77cddf5761a9cdf6d47bab64693a236603ab1db1a42f965cd37e3dad"
        data:
          type: string
          example:
            [
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 10,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 15,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 20,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 25,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 30,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 35,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 40,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 45,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 10,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 15,
              },
              {
                "address": "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
                "amount": 20,
              },
            ]
      required:
        - rune_id
        - feeRate
        - txid
        - data

    sameAmount:
      type: object
      properties:
        rune_id:
          type: string
          example: "2822267:1023"
        feeRate:
          type: number
          example: 25
        amount:
          type: number
          example: 10
        addressList:
          type: string
          example:
            [
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
              "tb1pqu4ty7cc065rtl83jxxsyrjtgl4gkyxwx8v448w947ukeszh5lzqmguhu2",
            ]
      required:
        - rune_id
        - feeRate
        - amount
        - addressList

    EstimateDifferentAmount:
      type: object
      properties:
        feeRate:
          type: number
          example: 25
        size:
          type: number
          example: 5000
      required:
        - feeRate
        - size

    EstimateSameAmount:
      type: object
      properties:
        feeRate:
          type: number
          example: 25
        size:
          type: number
          example: 5000
      required:
        - feeRate
        - size
